"""empty message

Revision ID: 2bbd788fd620
Revises: 26e6ab010f53
Create Date: 2025-07-02 22:06:45.938164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bbd788fd620'
down_revision: Union[str, Sequence[str], None] = '26e6ab010f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comment_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('products', sa.Column('sum_rewies', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('count_rewies', sa.Integer(), nullable=True))
    op.drop_column('products', 'all_rewies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('all_rewies', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('products', 'count_rewies')
    op.drop_column('products', 'sum_rewies')
    op.alter_column('comments', 'comment_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
